### ISSUE TITLE
New Patches

### ISSUE THREAD

**Issue by Androxilogin** [enriquesomolinos/pkgripper-patches#10]
|Game              |  Orig. Base  |  Base Ripped  |  Orig. Update  |  Update Ripped  |  Space Saved
Stardew v1.58          167               64.4                    314                    314                     103 

UP2456-CUSA06840_00-STARDEW00000SIEA-A0100-V0100
UP2456-CUSA06840_00-STARDEW00000SIEA-A0158-V0100

[Stardew v1.58](https://github.com/enriquesomolinos/pkgripper-patches/files/7965137/UP2456-CUSA06840_00-STARDEW00000SIEA.zip)

[Here are a number of others. No details. ](https://github.com/enriquesomolinos/pkgripper-patches/files/7965142/patches.zip)
Sekiro, The Last of Us, DELTARUNE Chapter 1, Quake, Horizon: Zero Dawn, Alwa's Legacy, Farming Simulator 22, Crosscode.

**Comment by enriquesomolinos** [comment]
Thanks for your colaboration!
