### ISSUE TITLE
MEDIEVIL HD - CUSA12982 

### ISSUE THREAD

**Issue by RunAway189** [enriquesomolinos/pkgripper-patches#11]
Hello, 

I tried to rip this game but sadly the latest update from this database is 1.01 instead of 1.02. Could you please update it? Thanks in advance

**Comment by PhR34x0r** [comment]
You can always create the patch yourself, please try and see if this is useful:
https://github.com/enriquesomolinos/pkgRipper/files/8004824/PKGRipper.Manual.pdf

**Comment by PhR34x0r** [comment]
Alright i did it myself, here you go
[EP9000-CUSA12982_00-MEDIEVILHD000001.zip](https://github.com/enriquesomolinos/pkgripper-patches/files/8006294/EP9000-CUSA12982_00-MEDIEVILHD000001.zip)

**Comment by PhR34x0r** [comment]
Extract this into the patches folder, it should work:
[EP9000-CUSA12982_00-MEDIEVILHD000001.zip](https://github.com/enriquesomolinos/pkgripper-patches/files/8006324/EP9000-CUSA12982_00-MEDIEVILHD000001.zip)

**Comment by enriquesomolinos** [comment]
Thanks [PhR34x0r](https://github.com/PhR34x0r)
