### ISSUE TITLE
6 more patches

### ISSUE THREAD

**Issue by PhR34x0r** [enriquesomolinos/pkgripper-patches#13]
Apex Construct
Smash Hit Plunder
Red Matter
[patches.zip](https://github.com/enriquesomolinos/pkgripper-patches/files/8005469/patches.zip)

**Comment by PhR34x0r** [comment]
Uncharted Trilogy, 4, Lost Legacy
[patches.zip](https://github.com/enriquesomolinos/pkgripper-patches/files/8015705/patches.zip)

**Comment by enriquesomolinos** [comment]
Added, thanks [PhR34x0r](https://github.com/PhR34x0r)
