### ISSUE TITLE
Just to know

### ISSUE THREAD

**Issue by chronoss09** [enriquesomolinos/pkgripper-patches#3]
All your file for rip game, you delete all language and movie or we have the choise for item to delete ? exp for FARCRY6

Sorry for my bad english :(

**Comment by enriquesomolinos** [comment]
Hi @chronoss09 , you can select what langague you want. It depends the person how create the patches for the game, it his responsability to create separate patches for language, video removal

**Comment by chronoss09** [comment]
Yes i know, it's a hard work to do but all of your file are based for english langage only ?

**Comment by enriquesomolinos** [comment]
No, I try to create a patch for each language separatelly. I want this patches to be use by anyone, no matter what language is

**Comment by chronoss09** [comment]
Good, i take all update and maybe i will have the patch that i needed :)

Good luck :)

**Comment by chronoss09** [comment]
On Far Cry 6, what language you leave ?

**Comment by enriquesomolinos** [comment]
you have a patch for each language you want

**Comment by chronoss09** [comment]
thanks but can't open any pkg :(
