### ISSUE TITLE
A few questions.

### ISSUE THREAD

**Issue by Androxilogin** [enriquesomolinos/pkgripper-patches#5]
Okay, so I'm making some patches but there are things I don't understand.

Say, The Last of Us..

I've gone through and marked down files to remove all languages but one, fine. Hit the button to remove duplicates from update. There were none. Created a patch description, **Pkg required version** left at default (01.00) and left **Update required version** blank.

Now when I create my package file with the English option in place, will I be able to install the update over top of this without any further action or will I have to do the whole remarry process:

</patch>
    <patch description="fake patch to link the update with your base.pkg file" pkg_required_version="01.01" update_version_required="01.01"/>        
</patches>

And with this, if my patch is, say, 1.42, would I change portions of it to: **pkg_required_version="01.42" update_version_required="01.42** ??

A lot of the details here are very vague. Even "tutorials" people are making don't actually explain what is going on, just simply saying 'do this' rather than what things do or what to watch out for that would cause mistakes. I've done a few patches so far but the ones with updates have failed for the most part and I don't understand why. 

For the MediEvil patch I provided here the other day, I'm not sure if it would work correctly with the update file or not. I just basically took from what was already there and changed the CUSA code. It would be nice to see an official video tutorial from the author. What I have seen so far hasn't been helpful in the least bit. And actually, I'm not even sure what all questions I had but figured I would start with what was bugging me the most.

**Comment by enriquesomolinos** [comment]
try this video https://youtu.be/Mu0N7axnWpg

**Comment by Androxilogin** [comment]
> try this video https://youtu.be/Mu0N7axnWpg

That's actually one of the videos I was referring to. It doesn't answer these questions, only give the basic idea of how it is meant to operate.

**Comment by PhR34x0r** [comment]
I get what you mean. The part about remarrying the patch with the game bugs me out: why use both original files? shouldnt the update be used on the trimmed game file?

**Comment by Androxilogin** [comment]
Yep, installing updates has an error every single time. Tried with multiple games, tried different values. 

tried:

<patch description="fake patch to link the update with your base.pkg file" pkg_required_version="01.07" update_version_required="01.07"/>

tried:

<patch description="fake patch to link the update with your base.pkg file" pkg_required_version="01.00" update_version_required="01.07"/>

(Assumed this would be correct; video said 

This time, got an error of CE-36434-0. 

I would have added a number of patches so far if I could get any of them to work.

**Comment by Androxilogin** [comment]
Okay, okay. I got it to work. Last comment was deleted because it had coding that I used which didn't show up. 

@PhR34x0r Yes, it works with the trimmed files. Part of my problem was he used a simple 01.01 file update so I wasn't sure if this had to be updated to the version the file says it is or what since he said to **MAKE SURE IT'S EXACTLY THE SAME**, which you can obviously edit the description to whatever you'd like, as you should. Also, I wasn't understanding pkg_required_version="01.07" update_version_required="01.07". It seemed like the first portion should be pkg_required_version="01.00". 

And finally, checking out the last time, I realized the program doesn't redirect you to the trimmed file, you have to move to it manually when choosing the base pkg for the patch. 

Anyway, patches incoming!
